export const users = [
    {
        id:1,
        name:"მარიამი",
        age:19,
        role:"Admin",
        skills:["javascript","UX/UI","Python"],
        photo:"https://fastly.picsum.photos/id/1049/200/400.jpg?hmac=nl8cekDbBWRuDLEawHNXDpv0ljB-hgKYoxD_WvH_Enw"
    },
    {
        id:2,
        name:"ნიკა",
        age:21,
        role:"User",
        skills:["javascript","UX/UI","Python"],
        photo:"https://fastly.picsum.photos/id/1049/200/400.jpg?hmac=nl8cekDbBWRuDLEawHNXDpv0ljB-hgKYoxD_WvH_Enw"
    },
    {
        id:3,
        name:"მარიამი",
        age:38,
        role:"User",
        skills:["javascript","UX/UI","Python"],
        photo:"https://fastly.picsum.photos/id/1049/200/400.jpg?hmac=nl8cekDbBWRuDLEawHNXDpv0ljB-hgKYoxD_WvH_Enw"
    },
    {
        id:4,
        name:"გიორგი",
        age:18,
        role:"Admin",
        skills:["javascript","UX/UI","Python"],
        photo:"https://fastly.picsum.photos/id/1049/200/400.jpg?hmac=nl8cekDbBWRuDLEawHNXDpv0ljB-hgKYoxD_WvH_Enw"
    },
    {
        id:5,
        name:"ნიკა",
        age:18,
        role:"Admin",
        skills:["javascript","UX/UI","Python"],
        photo:"https://fastly.picsum.photos/id/1049/200/400.jpg?hmac=nl8cekDbBWRuDLEawHNXDpv0ljB-hgKYoxD_WvH_Enw"
    },
]